export const TYPE = {
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  MOUSE_MOVE: "MOUSE_MOVE",
  UPDATE_SCHEDULE: "UPDATE_SCHEDULE",
  ADD_SCHEDULE: "ADD_SCHEDULE",
  REMOVE_SCHEDULE: "REMOVE_SCHEDULE",
};
