export const TYPE = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  MOUSE_MOVE: "MOUSE_MOVE",
  PIN_MARK: "PIN_MARK",
  DELETE_MARK: "DELETE_MARK",
  UPDATE_SCHEDULE: "UPDATE_SCHEDULE",
  ADD_SCHEDULE: "ADD_SCHEDULE",
  REMOVE_SCHEDULE: "REMOVE_SCHEDULE",
};
